import styles from "@/styles/Home.module.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import IceCreamBuilder from "./containers/IceCreamBuilder/IceCreamBuilder.jsx";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
				<title>React and NextJs Ice Cream Builder</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
      <main className={`${styles.mainBody} ${inter.className}`}>
        <IceCreamBuilder/>
      </main>
    </>
  );
}
